---
abstract: 'calculate lines'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Exporter: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::Output: 0
  parent: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-LogStats
provides:
  App::LogStats:
    file: lib/App/LogStats.pm
    version: 0.091
requires:
  Class::Accessor::Lite: 0
  Getopt::Long: 2.38
  IO::Interactive::Tiny: 0
  Pod::Usage: 0
  Text::ASCIITable: 0.2
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/App-LogStats
version: 0.091
